version: '3.8'

services:
  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - "8501:8501"

  taxi_fare:
    build:
      context: ./taxi_fare
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - model
